LRB:
  sample_rate: 64
  batch_size: 131072
  max_n_past_timestamps: 32
  num_iterations: 32
  num_leaves: 32
  num_threads: 4
  learning_rate: 0.1
  objective: byte_miss_ratio
  n_edc_feature: 10
  version: auto_search_memory_window
